import type { ConstellationConfig, GhostConfig } from '@vora/mycelial-engine'

export const CHIRALITY_CONFIG: ConstellationConfig = {
  name: 'chirality',
  color: 0xF7931A,
  colorDim: 0xc47515,
  colorCSS: '#F7931A',
  colorBoth: 0xD4A853,
  colorBothCSS: '#D4A853',
  featuredNode: 'the-constellation',
  readingOrder: [
    'the-constellation',
    'the-handedness-of-being',
    'theses-on-chirality',
    'the-five-completions',
    '05-the-filter',
    'chirality-agamben',
    'care-can-now-be-proved',
    'chirality',
    'the-chiral-completion',
    'chiral-pedagogy',
    '06-dwelling-in-the-digital-age',
    'the-proof-of-love',
    '11-the-event-of-logic',
    'the-passage',
    'tuesday-in-the-clearing',
    'the-cete',
  ],
  clusterCenter: { x: 0, y: 0 },
  bloom: { strength: 1.2, threshold: 0.5, radius: 0.8 },
}

export const GHOST_CONFIG: GhostConfig = {
  remoteGraphUrl: 'https://coindork.github.io/cryptosovereignty/graph.json',
  remoteColor: 0x00B4D8,
  remoteColorCSS: '#00B4D8',
  remoteName: 'cryptosovereignty',
  remoteSiteUrl: 'https://coindork.github.io/cryptosovereignty/',
}

export const CRYPTO_REMOTE_CONFIG: ConstellationConfig = {
  name: 'cryptosovereignty',
  color: 0x00B4D8,
  colorDim: 0x0096C7,
  colorCSS: '#00B4D8',
  colorBoth: 0x4ECDC4,
  colorBothCSS: '#4ECDC4',
  featuredNode: 'ext-the-event-and-the-clearing',
  readingOrder: [
    'ext-the-event-and-the-clearing',
    '01-cryptosovereignty',
    '02-the-encrypted-meaning-of-crypto',
    '03-the-new-form-of-power',
    '04-crypto-truth-and-power',
    '05-the-political-theology-of-crypto',
    '06-crypto-without-criticisms',
    '07-the-sovereign-the-subject',
    '08-the-theological-conquest-of-money',
    '09-the-legend-of-satoshi-nakamoto',
    '10-the-concept-of-the-political',
    '11-the-oath-of-machines',
    '12-messianic-bitcoin',
    '13-the-pedagogy-of-bitcoin',
    '14-the-political-theology-of-bitcoin',
    '15-bitcoin-and-the-state-of-emergency',
    '16-theory-of-the-crypto-partisan',
    '17-to-my-crypto-comrades',
    '18-the-hope-of-bitcoin',
    '19-bitcoin-and-the-conquest-of-privacy',
    '20-the-question-concerning-bitcoin',
    'ext-first-philosophy',
    'ext-sovereign-mutualism',
    'ext-the-solitary-sovereign',
  ],
  clusterCenter: { x: -200, y: 0 },
  bloom: { strength: 1.2, threshold: 0.5, radius: 0.8 },
}
